/* Load this script using conditional IE comments if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'service-icons\'">' + entity + '</span>' + html;
	}
	var icons = {
			'serviceicon-write' : '&#x21;',
			'serviceicon-wifi' : '&#x22;',
			'serviceicon-vineglass' : '&#x23;',
			'serviceicon-video' : '&#x24;',
			'serviceicon-vcard' : '&#x25;',
			'serviceicon-vault' : '&#x26;',
			'serviceicon-user2' : '&#x27;',
			'serviceicon-user' : '&#x28;',
			'serviceicon-unlocked' : '&#x29;',
			'serviceicon-umbrella' : '&#x2a;',
			'serviceicon-truck' : '&#x2b;',
			'serviceicon-tree' : '&#x2c;',
			'serviceicon-trashcan2' : '&#x2d;',
			'serviceicon-trashcan' : '&#x2e;',
			'serviceicon-tools' : '&#x2f;',
			'serviceicon-tag2' : '&#x30;',
			'serviceicon-tag' : '&#x31;',
			'serviceicon-support' : '&#x32;',
			'serviceicon-sunglasses' : '&#x33;',
			'serviceicon-strategy2' : '&#x34;',
			'serviceicon-strategy' : '&#x35;',
			'serviceicon-stopwatch' : '&#x36;',
			'serviceicon-speaker' : '&#x37;',
			'serviceicon-sign' : '&#x38;',
			'serviceicon-shopcart2' : '&#x39;',
			'serviceicon-shopcart' : '&#x3a;',
			'serviceicon-settings' : '&#x3b;',
			'serviceicon-scissors' : '&#x3c;',
			'serviceicon-safari' : '&#x3d;',
			'serviceicon-rss' : '&#x3e;',
			'serviceicon-refresh2' : '&#x3f;',
			'serviceicon-refresh' : '&#x40;',
			'serviceicon-recyclebag' : '&#x41;',
			'serviceicon-preview' : '&#x42;',
			'serviceicon-power2' : '&#x43;',
			'serviceicon-power' : '&#x44;',
			'serviceicon-postcard' : '&#x45;',
			'serviceicon-piechart' : '&#x46;',
			'serviceicon-phone' : '&#x47;',
			'serviceicon-pen2' : '&#x48;',
			'serviceicon-pen' : '&#x49;',
			'serviceicon-pdf2' : '&#x4a;',
			'serviceicon-pdf' : '&#x4b;',
			'serviceicon-paperclip' : '&#x4c;',
			'serviceicon-pacman' : '&#x4d;',
			'serviceicon-mouse' : '&#x4e;',
			'serviceicon-microphone' : '&#x4f;',
			'serviceicon-marker' : '&#x50;',
			'serviceicon-map' : '&#x51;',
			'serviceicon-mail2' : '&#x52;',
			'serviceicon-mail' : '&#x53;',
			'serviceicon-magnifier2' : '&#x54;',
			'serviceicon-magnifier' : '&#x55;',
			'serviceicon-mac' : '&#x56;',
			'serviceicon-locked' : '&#x57;',
			'serviceicon-list2' : '&#x58;',
			'serviceicon-list' : '&#x59;',
			'serviceicon-link2' : '&#x5a;',
			'serviceicon-link' : '&#x5b;',
			'serviceicon-leaf' : '&#x5c;',
			'serviceicon-laptop' : '&#x5d;',
			'serviceicon-iphone' : '&#x5e;',
			'serviceicon-ipad2' : '&#x5f;',
			'serviceicon-ipad' : '&#x60;',
			'serviceicon-info' : '&#x61;',
			'serviceicon-image4' : '&#x62;',
			'serviceicon-image3' : '&#x63;',
			'serviceicon-image2' : '&#x64;',
			'serviceicon-image' : '&#x65;',
			'serviceicon-icecream' : '&#x66;',
			'serviceicon-hotspot' : '&#x67;',
			'serviceicon-home' : '&#x68;',
			'serviceicon-headphones' : '&#x69;',
			'serviceicon-halloween' : '&#x6a;',
			'serviceicon-group2' : '&#x6b;',
			'serviceicon-group' : '&#x6c;',
			'serviceicon-grid' : '&#x6d;',
			'serviceicon-globe2' : '&#x6e;',
			'serviceicon-globe' : '&#x6f;',
			'serviceicon-glass' : '&#x70;',
			'serviceicon-folder-user' : '&#x71;',
			'serviceicon-folder-music' : '&#x72;',
			'serviceicon-folder-locked' : '&#x73;',
			'serviceicon-folder' : '&#x74;',
			'serviceicon-flag2' : '&#x75;',
			'serviceicon-flag' : '&#x76;',
			'serviceicon-firefox' : '&#x77;',
			'serviceicon-film-camera' : '&#x78;',
			'serviceicon-film2' : '&#x79;',
			'serviceicon-film' : '&#x7a;',
			'serviceicon-files-cabinet' : '&#x7b;',
			'serviceicon-expand2' : '&#x7c;',
			'serviceicon-expand' : '&#x7d;',
			'serviceicon-download2' : '&#x7e;',
			'serviceicon-download' : '&#xe000;',
			'serviceicon-document2' : '&#xe001;',
			'serviceicon-document' : '&#xe002;',
			'serviceicon-display' : '&#xe003;',
			'serviceicon-cup' : '&#xe004;',
			'serviceicon-company' : '&#xe005;',
			'serviceicon-comment4' : '&#xe006;',
			'serviceicon-comment3' : '&#xe007;',
			'serviceicon-comment2' : '&#xe008;',
			'serviceicon-comment1' : '&#xe009;',
			'serviceicon-cog3' : '&#xe00a;',
			'serviceicon-cog2' : '&#xe00b;',
			'serviceicon-cog' : '&#xe00c;',
			'serviceicon-cloud-upload' : '&#xe00d;',
			'serviceicon-cloud-lightning' : '&#xe00e;',
			'serviceicon-cloud-download' : '&#xe00f;',
			'serviceicon-cloud' : '&#xe010;',
			'serviceicon-clock2' : '&#xe011;',
			'serviceicon-clock' : '&#xe012;',
			'serviceicon-clapboard' : '&#xe013;',
			'serviceicon-chrome' : '&#xe014;',
			'serviceicon-chemical' : '&#xe015;',
			'serviceicon-chart2' : '&#xe016;',
			'serviceicon-chart' : '&#xe017;',
			'serviceicon-car' : '&#xe018;',
			'serviceicon-camera2' : '&#xe019;',
			'serviceicon-camera' : '&#xe01a;',
			'serviceicon-calendar2' : '&#xe01b;',
			'serviceicon-calendar' : '&#xe01c;',
			'serviceicon-bulb' : '&#xe01d;',
			'serviceicon-buildings' : '&#xe01e;',
			'serviceicon-brush' : '&#xe01f;',
			'serviceicon-briefcase' : '&#xe020;',
			'serviceicon-books' : '&#xe021;',
			'serviceicon-book' : '&#xe022;',
			'serviceicon-blackberry' : '&#xe023;',
			'serviceicon-bell2' : '&#xe024;',
			'serviceicon-bell' : '&#xe025;',
			'serviceicon-battery' : '&#xe026;',
			'serviceicon-baloon' : '&#xe027;',
			'serviceicon-arrow-up' : '&#xe028;',
			'serviceicon-arrow-right' : '&#xe029;',
			'serviceicon-arrow-left' : '&#xe02a;',
			'serviceicon-arrow-down' : '&#xe02b;',
			'serviceicon-archive' : '&#xe02c;',
			'serviceicon-applications' : '&#xe02d;',
			'serviceicon-android' : '&#xe02e;',
			'serviceicon-alert2' : '&#xe02f;',
			'serviceicon-alert' : '&#xe030;',
			'serviceicon-airplane' : '&#xe031;',
			'serviceicon-admin' : '&#xe032;',
			'serviceicon-addressbook' : '&#xe033;',
			'serviceicon-access' : '&#xe034;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, html, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/serviceicon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
};