<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Banner_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get banner by bid
     */
    function get_banner($bid)
    {
        return $this->db->get_where('banner',array('bid'=>$bid))->row_array();
    }
    
    /*
     * Get all banner
     */
    function get_all_banner()
    {
        return $this->db->get('banner')->result_array();
    }
    
    /*
     * function to add new banner
     */
    function add_banner($params)
    {
        $this->db->insert('banner',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update banner
     */
    function update_banner($bid,$params)
    {
        $this->db->where('bid',$bid);
        $response = $this->db->update('banner',$params);
        if($response)
        {
            return "banner updated successfully";
        }
        else
        {
            return "Error occuring while updating banner";
        }
    }
    
    /*
     * function to delete banner
     */
    function delete_banner($bid)
    {
        $response = $this->db->delete('banner',array('bid'=>$bid));
        if($response)
        {
            return "banner deleted successfully";
        }
        else
        {
            return "Error occuring while deleting banner";
        }
    }
}
