<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Log_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    

    
    /*
     * function to add new log
     */
    function add_log($params)
    {
        $this->db->insert('logs',$params);
        return $this->db->insert_id();
    }
    

}
