<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Product_sub_category_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get product_sub_category by sid
     */
    function get_product_sub_category($sid)
    {
        return $this->db->get_where('product_sub_categories',array('sid'=>$sid))->row_array();
    }
    
    /*
     * Get all product_sub_categories
     */
    function get_all_product_sub_categories()
    {
        return $this->db->get('product_sub_categories')->result_array();
    }
    
    /*
     * function to add new product_sub_category
     */
    function add_product_sub_category($params)
    {
        $this->db->insert('product_sub_categories',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update product_sub_category
     */
    function update_product_sub_category($sid,$params)
    {
        $this->db->where('sid',$sid);
        $response = $this->db->update('product_sub_categories',$params);
        if($response)
        {
            return "product_sub_category updated successfully";
        }
        else
        {
            return "Error occuring while updating product_sub_category";
        }
    }
    
    /*
     * function to delete product_sub_category
     */
    function delete_product_sub_category($sid)
    {
        $response = $this->db->delete('product_sub_categories',array('sid'=>$sid));
        if($response)
        {
            return "product_sub_category deleted successfully";
        }
        else
        {
            return "Error occuring while deleting product_sub_category";
        }
    }
}
