<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Product_category_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get product_category by cid
     */
    function get_product_category($cid)
    {
        return $this->db->get_where('product_categories',array('cid'=>$cid))->row_array();
    }
    
    /*
     * Get all product_categories
     */
    function get_all_product_categories()
    {
        return $this->db->get('product_categories')->result_array();
    }
    
    /*
     * function to add new product_category
     */
    function add_product_category($params)
    {
        $this->db->insert('product_categories',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update product_category
     */
    function update_product_category($cid,$params)
    {
        $this->db->where('cid',$cid);
        $response = $this->db->update('product_categories',$params);
        if($response)
        {
            return "product_category updated successfully";
        }
        else
        {
            return "Error occuring while updating product_category";
        }
    }
    
    /*
     * function to delete product_category
     */
    function delete_product_category($cid)
    {
        $response = $this->db->delete('product_categories',array('cid'=>$cid));
        if($response)
        {
            return "product_category deleted successfully";
        }
        else
        {
            return "Error occuring while deleting product_category";
        }
    }
}
