<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Banner extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Banner_model');
    } 

    /*
     * Listing of banner
     */
    function index()
    {
        $data['banner'] = $this->Banner_model->get_all_banner();

        $data['_view'] = 'banner/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new banner
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('image','Image','required');
		$this->form_validation->set_rules('visible','Visible','required');
		$this->form_validation->set_rules('delay','Delay','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'visible' => $this->input->post('visible'),
				'image' => $this->input->post('image'),
				'link' => $this->input->post('link'),
				'delay' => $this->input->post('delay'),
            );
            
            $banner_id = $this->Banner_model->add_banner($params);
            redirect('banner/index');
        }
        else
        {            
            $data['_view'] = 'banner/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a banner
     */
    function edit($bid)
    {   
        // check if the banner exists before trying to edit it
        $data['banner'] = $this->Banner_model->get_banner($bid);
        
        if(isset($data['banner']['bid']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('image','Image','required');
			$this->form_validation->set_rules('visible','Visible','required');
			$this->form_validation->set_rules('delay','Delay','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'visible' => $this->input->post('visible'),
					'image' => $this->input->post('image'),
					'link' => $this->input->post('link'),
					'delay' => $this->input->post('delay'),
                );

                $this->Banner_model->update_banner($bid,$params);            
                redirect('banner/index');
            }
            else
            {
                $data['_view'] = 'banner/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The banner you are trying to edit does not exist.');
    } 

    /*
     * Deleting banner
     */
    function remove($bid)
    {
        $banner = $this->Banner_model->get_banner($bid);

        // check if the banner exists before trying to delete it
        if(isset($banner['bid']))
        {
            $this->Banner_model->delete_banner($bid);
            redirect('banner/index');
        }
        else
            show_error('The banner you are trying to delete does not exist.');
    }
    
}
