<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Log extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Log_model');
    } 

    /*
     * Listing of logs
     */
    function index()
    {
        $data['_view'] = 'admin/log/index';
        $this->load->view('admin/layouts/main',$data);
    }

    /*
     * Adding a new log
     */
    function ajax()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'log_date' => $this->input->post('log_date'),
				'user' => $this->input->post('user'),
				'detail' => $this->input->post('detail'),
            );
            
            $log_id = $this->Log_model->add_log($params);
            redirect('log/index');
        }
        else
        {            
            $data['_view'] = 'log/add';
            $this->load->view('layouts/main',$data);
        }
    }
}
