<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Product extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Product_model');
    } 

    /*
     * Listing of products
     */
    function index()
    {
        $data['products'] = $this->Product_model->get_all_products();

        $data['_view'] = 'product/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new product
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('product_title','Product Title','required|is_unique[product_title]');
		$this->form_validation->set_rules('product_photo','Product Photo','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'product_category' => $this->input->post('product_category'),
				'product_online' => $this->input->post('product_online'),
				'product_title' => $this->input->post('product_title'),
				'product_photo' => $this->input->post('product_photo'),
				'product_group' => $this->input->post('product_group'),
				'product_pdf' => $this->input->post('product_pdf'),
				'product_price' => $this->input->post('product_price'),
				'product_spacial_price' => $this->input->post('product_spacial_price'),
				'product_description' => $this->input->post('product_description'),
            );
            
            $product_id = $this->Product_model->add_product($params);
            redirect('product/index');
        }
        else
        {
			$this->load->model('Product_sub_category_model');
			$data['all_product_sub_categories'] = $this->Product_sub_category_model->get_all_product_sub_categories();
            
            $data['_view'] = 'product/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a product
     */
    function edit($pid)
    {   
        // check if the product exists before trying to edit it
        $data['product'] = $this->Product_model->get_product($pid);
        
        if(isset($data['product']['pid']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('product_title','Product Title','required|is_unique[product_title]');
			$this->form_validation->set_rules('product_photo','Product Photo','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'product_category' => $this->input->post('product_category'),
					'product_online' => $this->input->post('product_online'),
					'product_title' => $this->input->post('product_title'),
					'product_photo' => $this->input->post('product_photo'),
					'product_group' => $this->input->post('product_group'),
					'product_pdf' => $this->input->post('product_pdf'),
					'product_price' => $this->input->post('product_price'),
					'product_spacial_price' => $this->input->post('product_spacial_price'),
					'product_description' => $this->input->post('product_description'),
                );

                $this->Product_model->update_product($pid,$params);            
                redirect('product/index');
            }
            else
            {
				$this->load->model('Product_sub_category_model');
				$data['all_product_sub_categories'] = $this->Product_sub_category_model->get_all_product_sub_categories();

                $data['_view'] = 'product/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The product you are trying to edit does not exist.');
    } 

    /*
     * Deleting product
     */
    function remove($pid)
    {
        $product = $this->Product_model->get_product($pid);

        // check if the product exists before trying to delete it
        if(isset($product['pid']))
        {
            $this->Product_model->delete_product($pid);
            redirect('product/index');
        }
        else
            show_error('The product you are trying to delete does not exist.');
    }
    
}
