<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Product_category extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Product_category_model');
    } 

    /*
     * Listing of product_categories
     */
    function index()
    {
        $data['product_categories'] = $this->Product_category_model->get_all_product_categories();

        $data['_view'] = 'product_category/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new product_category
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('title','Title','required|is_unique[title]');
		$this->form_validation->set_rules('priority','Priority','required|integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'title' => $this->input->post('title'),
				'priority' => $this->input->post('priority'),
				'description' => $this->input->post('description'),
            );
            
            $product_category_id = $this->Product_category_model->add_product_category($params);
            redirect('product_category/index');
        }
        else
        {            
            $data['_view'] = 'product_category/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a product_category
     */
    function edit($cid)
    {   
        // check if the product_category exists before trying to edit it
        $data['product_category'] = $this->Product_category_model->get_product_category($cid);
        
        if(isset($data['product_category']['cid']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('title','Title','required|is_unique[title]');
			$this->form_validation->set_rules('priority','Priority','required|integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'title' => $this->input->post('title'),
					'priority' => $this->input->post('priority'),
					'description' => $this->input->post('description'),
                );

                $this->Product_category_model->update_product_category($cid,$params);            
                redirect('product_category/index');
            }
            else
            {
                $data['_view'] = 'product_category/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The product_category you are trying to edit does not exist.');
    } 

    /*
     * Deleting product_category
     */
    function remove($cid)
    {
        $product_category = $this->Product_category_model->get_product_category($cid);

        // check if the product_category exists before trying to delete it
        if(isset($product_category['cid']))
        {
            $this->Product_category_model->delete_product_category($cid);
            redirect('product_category/index');
        }
        else
            show_error('The product_category you are trying to delete does not exist.');
    }
    
}
