<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */

class Setting extends CI_Controller{
   public $render_data = array();

    public function __construct() {
        parent::__construct();

        $this->template->set_template('admin');
        $this->load->model('Setting_model','setting');
    }


    /*
     * Editing a setting
     */
    public function index()
    {   
        if(!is_group('admin')){
            redirect('admin');
            exit();
        }
        // check if the setting exists before trying to edit it
        $data['setting'] = $this->setting->get_setting();
        
        if(isset($data['setting']['sid']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                   'site_title' => $this->input->post('site_title'),
                   'site_keyword' => $this->input->post('site_keyword'),
                   'facebook' => $this->input->post('facebook'),
                   'google' => $this->input->post('google'),
                   'instagram' => $this->input->post('instagram'),
                   'site_description' => $this->input->post('site_description'),
                   );

                $this->setting->update_setting($params);            
                redirect('setting');
            }
            else
            {
                //******* Defalut ********//
        $render_data['user'] = $this->session->userdata('fnsn');
        $this->template->write('title', 'News');
        $this->template->write('user_id', $render_data['user']['aid']);
        $this->template->write('user_name', $render_data['user']['name']);
        $this->template->write('user_group', $render_data['user']['group']);
        //******* Defalut ********//
             $this->template->write_view('content', 'admin/setting/edit', $render_data);
             $this->template->render();
         }
     }
     else
        show_error('The setting you are trying to edit does not exist.');
}
}
