<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class User extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_model');
    } 

    /*
     * Listing of users
     */
    function index()
    {
        $data['users'] = $this->User_model->get_all_users();

        $data['_view'] = 'user/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new user
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('account_type','Account Type','required');
		$this->form_validation->set_rules('password','Password','required|min_length[6]|max_length[50]');
		$this->form_validation->set_rules('email','Email','required|valid_email|is_unique[users.email]');
		$this->form_validation->set_rules('name','Name','required|max_length[100]');
		$this->form_validation->set_rules('sname','Sname','required|max_length[100]');
		$this->form_validation->set_rules('phone','Phone','required|max_length[20]');
		$this->form_validation->set_rules('shiping_name','Shiping Name','required|max_length[200]');
		$this->form_validation->set_rules('shiping_province','Shiping Province','required');
		$this->form_validation->set_rules('shiping_zip','Shiping Zip','required|numeric|min_length[5]|max_length[5]');
		$this->form_validation->set_rules('shiping_address','Shiping Address','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'account_type' => $this->input->post('account_type'),
				'staf_id' => $this->input->post('staf_id'),
				'password' => $this->input->post('password'),
				'email' => $this->input->post('email'),
				'name' => $this->input->post('name'),
				'sname' => $this->input->post('sname'),
				'phone' => $this->input->post('phone'),
				'shiping_name' => $this->input->post('shiping_name'),
				'shiping_province' => $this->input->post('shiping_province'),
				'shiping_zip' => $this->input->post('shiping_zip'),
				'shiping_address' => $this->input->post('shiping_address'),
            );
            
            $user_id = $this->User_model->add_user($params);
            redirect('user/index');
        }
        else
        {
			$this->load->model('Admin_model');
			$data['all_admins'] = $this->Admin_model->get_all_admins();
            
            $data['_view'] = 'user/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a user
     */
    function edit($uid)
    {   
        // check if the user exists before trying to edit it
        $data['user'] = $this->User_model->get_user($uid);
        
        if(isset($data['user']['uid']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('account_type','Account Type','required');
			$this->form_validation->set_rules('password','Password','required|min_length[6]|max_length[50]');
			$this->form_validation->set_rules('email','Email','required|valid_email|is_unique[users.email]');
			$this->form_validation->set_rules('name','Name','required|max_length[100]');
			$this->form_validation->set_rules('sname','Sname','required|max_length[100]');
			$this->form_validation->set_rules('phone','Phone','required|max_length[20]');
			$this->form_validation->set_rules('shiping_name','Shiping Name','required|max_length[200]');
			$this->form_validation->set_rules('shiping_province','Shiping Province','required');
			$this->form_validation->set_rules('shiping_zip','Shiping Zip','required|numeric|min_length[5]|max_length[5]');
			$this->form_validation->set_rules('shiping_address','Shiping Address','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'account_type' => $this->input->post('account_type'),
					'staf_id' => $this->input->post('staf_id'),
					'password' => $this->input->post('password'),
					'email' => $this->input->post('email'),
					'name' => $this->input->post('name'),
					'sname' => $this->input->post('sname'),
					'phone' => $this->input->post('phone'),
					'shiping_name' => $this->input->post('shiping_name'),
					'shiping_province' => $this->input->post('shiping_province'),
					'shiping_zip' => $this->input->post('shiping_zip'),
					'shiping_address' => $this->input->post('shiping_address'),
                );

                $this->User_model->update_user($uid,$params);            
                redirect('user/index');
            }
            else
            {
				$this->load->model('Admin_model');
				$data['all_admins'] = $this->Admin_model->get_all_admins();

                $data['_view'] = 'user/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The user you are trying to edit does not exist.');
    }
}
